name: Github action demo
on:
  push:
    branches:
      - main
      - master
      - develop
      - "release/**"
  pull_request:
    branches:
      - master
      
jobs:
  action-demo:
    runs-on: ubuntu-latest
    steps:
      - name: checkout the code
        uses: actions/checkout@v6
      - name: Print index.html file
        run: cat index.html
 
